Repository UBC-MDS/Group16_knnmodel, pull requests merged in 2024-01, with the labels that each got.

#15 Docstrings for predict
  src/pkg_pyknnclassifier/predict.py
Labels: project structure

#14 Docstrings for calculate_distance
  src/pkg_pyknnclassifier/calculate_distance.py
Labels: project structure

#21 Finished writing calculate_distance.py function
  src/pkg_pyknnclassifier/calculate_distance.py
Labels: enhancement

#30 Wrote test for calculate_distance.py
  tests/test-calculate_distance.py
Labels: enhancement

#36 Updated test and script for calculate_distance
  src/pkg_pyknnclassifier/calculate_distance.py
  tests/test-calculate_distance.py
Labels: enhancement

#32 Update readme for milestone 2
  README.md
Labels: documentation

#43 add test for coverage
  src/pkg_pyknnclassifier/evaluate.py
  tests/test_evaluate.py
Labels: enhancement

#58 minor update on the example
  docs/example.ipynb
Labels: documentation, meeting

#57 removed unused pyfile
  src/pkg_pyknnclassifier/pkg_pyknnclassifier.py
Labels: documentation, enhancement

#61 Fix peer review part 2
  README.md
Labels: bug, documentation

#62 Fixed README Part1
  README.md
Labels: bug, documentation

#63 fix: Feedback addressed by Shizhe and Weiran
  docs/example.ipynb
Labels: documentation, enhancement
