Repository UBC-MDS/Group16_knnmodel, pull requests merged in 2024-02, with the labels that each got.

#66 Modify according to milestone feedback
  src/pkg_pyknnclassifier/calculate_distance.py
  src/pkg_pyknnclassifier/evaluate.py
  src/pkg_pyknnclassifier/find_neighbors.py
  src/pkg_pyknnclassifier/scaling.py
  tests/test_evaluate.py
Labels: documentation, enhancement

#67 Addressing Milestone2 feedback
  src/pkg_pyknnclassifier/calculate_distance.py
  src/pkg_pyknnclassifier/evaluate.py
  src/pkg_pyknnclassifier/find_neighbors.py
  src/pkg_pyknnclassifier/predict.py
  src/pkg_pyknnclassifier/scaling.py
Labels: enhancement

#68 fix: milestone2 point 10
  src/pkg_pyknnclassifier/find_neighbors.py
  tests/test_find_neighbors.py
Labels: enhancement

#69 addressing MS2 Feadback, test structure
  tests/test-calculate_distance.py
Labels: documentation

#70 Addressed ML2 FB, added the comments, and update the format
  src/pkg_pyknnclassifier/data_loading.py
  tests/test_find_neighbors.py
  tests/test_predict.py
Labels: documentation, enhancement

#75 fix ms2 distance
  src/pkg_pyknnclassifier/calculate_distance.py
  tests/test-calculate_distance.py
Labels: enhancement

#76 fix: ms2 point 9, point 10, point 11
  src/pkg_pyknnclassifier/data_loading.py
  src/pkg_pyknnclassifier/find_neighbors.py
  src/pkg_pyknnclassifier/predict.py
  tests/test_data_loading.py
  tests/test_find_neighbors.py
  tests/test_predict.py
Labels: enhancement

#80 fix: add input checks for scaling
  src/pkg_pyknnclassifier/scaling.py
  tests/test_scaling.py
Labels: enhancement
